# my global config
global:
  scrape_interval: 100ms  # Adjust this as necessary
  evaluation_interval: 1s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["oracle_with_blockchain:8002", "blockchain:26660"]